# Generated by Django 2.1.5 on 2024-02-09 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20240209_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='tittle',
            new_name='title',
        ),
    ]
